### PR TITLE
vrap grids at NNLO

### PR DESCRIPTION
**Pull request by scarlehoff**
Addresses #13

For the central scale seems to work (pineappl and vrap produce the same result). It would be good to have a third code to properly check the results of course... (beyond the fact that they haven't changed since the initial version).

### CODE REVIEW

**Comment by scarlehoff** [comment]
The numbers are not absolutely crazy for the scale variations (which means that if I missed something at least it does not multiply a divergence).

In order to test the scale variations I can also generate a grid for r_muR=2, r_muF=0.5 for instance. @cschwan how do I get the results for that? What would `--scales 3` or `--scales 7` produce?

**Comment by cschwan** [comment]
@scarlehoff I suppose you can leave the scale variation set to its default (7-point scale variation), but give `convolute` the extra switch `-a` (short for `--absolute`), which will explicitly show you all seven scale-varied results.

**Comment by cschwan** [comment]
> In order to test the scale variations I can also generate a grid for r_muR=2, r_muF=0.5 for instance.

However, for this particular scale variation you'll need the 9-point one.

**Comment by scarlehoff** [comment]
Ok `-s 9 -a` is what I need. Thanks!

**Comment by scarlehoff** [comment]
Great, it works :)

Results computed "by hand":
```
(1,1) (0.5, 0.5) (2,1) (1,2) (2,2) (0.5, 2)
441   472        421   435  411   468
```

results produced by pineappl
```
Pineappl results:
bin       x0           x1        diff        (1,1)       (2,2)     (0.5,0.5)     (2,1)       (1,2)      (0.5,1)     (1,0.5)     (2,0.5)     (0.5,2)  
---+-------+-------+----+----+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------+-----------
  0 7.10428 7.10428 -0.2 -0.2 4.4126323e2 4.4126323e2 4.1193325e2 4.7313431e2 4.2144816e2 4.3644362e2 4.6793163e2 4.5582043e2 4.4179080e2 4.7050294e2
```

**Comment by cschwan** [comment]
> Results computed "by hand":

Do you have these results with more digits? For some of them the accuracy is a bit worse maybe - are they computed using separate MC runs? If so, what are the MC uncertainties for them?

**Comment by scarlehoff** [comment]
I added one extra digit (the mc error is around 0.1 for everyone).

The only one that worries me is (0.5, 2.0) but since (0.5, 2.0) is ok I'm less worried.

**Comment by cschwan** [comment]
This is what I find (differences are given in per mille):

```
      scale      diff
1     (1,1) 1.7326447
2     (2,2) 1.2961838
3 (0.5,0.5) 2.8281263
4     (2,1) 1.0645131
5     (1,2) 1.9366850
6   (2,0.5) 0.8853647
7   (0.5,2) 4.9187100
```

and the differences in multiples of the MC uncertainty (0.1):

```
      scale   sigma
1     (1,1)  7.6323
2     (2,2)  5.3325
3 (0.5,0.5) 13.3431
4     (2,1)  4.4816
5     (1,2)  8.4362
6   (2,0.5)  3.9080
7   (0.5,2) 23.0294
```

**Comment by scarlehoff** [comment]
yeah, as I said, 0.5-2 is the only one that worries me.
I wonder whether vrap implements its own alpha_s since the other bigger difference is 0.5,0.5.
I'll have a look at what happens at NLO when I have time.

**Comment by scarlehoff** [comment]
At NLO we have the same kind of differences. 

If you want we can do a proper check etc to know where the differences are coming from and all that, but I think most of it is due to the interpolation itself (already almost a 2 per-mille difference for (1,1)) which makes sense since we are subtracting numerical divergences inside the pineappl grid. Then these differences increase a bit more when the values grow (as alpha_s grow). 

I would consider these numbers as ok x)

**Pull request merged**
